{% set name = "rectangle-packer" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 64d18e4e2fb0bec05b3e6cf4f133a54677c3001061186dd93d8442568e3eaa17

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0
    - pip
    - python
    - setuptools >=69
  run:
    - python

test:
  imports:
    - rpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Penlect/rectangle-packer
  summary: Pack a set of rectangles into a bounding box with minimum area
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - BastianZim
